services:
  nano:
    image: public.ecr.aws/docker/library/eclipse-temurin:24
    container_name: nano
    restart: always
    ports:
      - '127.0.0.1:9000:9000'
    working_dir: /app
    volumes:
      - .:/app
    command: ['./run.sh']
