server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:nano.db
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      leak-detection-threshold: 10000
